// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_RuJ2G7m45J7lOk3lWwAcR_jm8769vE',
    appId: '1:597058511051:web:26197620f8434679aa7b4e',
    messagingSenderId: '597058511051',
    projectId: 'prahar-app-82378',
    authDomain: 'prahar-app-82378.firebaseapp.com',
    storageBucket: 'prahar-app-82378.firebasestorage.app',
    measurementId: 'G-S4GEZ89BN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6EAruLRmMZEMoZpqfIiSz93zomtO7DZ8',
    appId: '1:597058511051:android:a85f461e68303550aa7b4e',
    messagingSenderId: '597058511051',
    projectId: 'prahar-app-82378',
    storageBucket: 'prahar-app-82378.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-gwnHrtwYoat93JMU5tn4cYlOtftaWw',
    appId: '1:597058511051:ios:fcd104cf4f848f93aa7b4e',
    messagingSenderId: '597058511051',
    projectId: 'prahar-app-82378',
    storageBucket: 'prahar-app-82378.firebasestorage.app',
    iosBundleId: 'com.example.prahaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf-gwnHrtwYoat93JMU5tn4cYlOtftaWw',
    appId: '1:597058511051:ios:fcd104cf4f848f93aa7b4e',
    messagingSenderId: '597058511051',
    projectId: 'prahar-app-82378',
    storageBucket: 'prahar-app-82378.firebasestorage.app',
    iosBundleId: 'com.example.prahaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC_RuJ2G7m45J7lOk3lWwAcR_jm8769vE',
    appId: '1:597058511051:web:cf9ab78593a05d81aa7b4e',
    messagingSenderId: '597058511051',
    projectId: 'prahar-app-82378',
    authDomain: 'prahar-app-82378.firebaseapp.com',
    storageBucket: 'prahar-app-82378.firebasestorage.app',
    measurementId: 'G-NL3VK5JFG6',
  );

}